%define	gem_name hpricot

Summary:	Ruby HTML parser
Name:		rubygem-%{gem_name}
Version:	0.8.6
Release:	1
Group:		Development/Ruby
License:	GPLv2+ or Ruby
URL:		https://rubygems.org/gems/hpricot
Source0:	https://rubygems.org/downloads/hpricot-0.8.6.gem
BuildRequires:	rubygems
BuildRequires:  ruby-devel

%description
Ruby HTML parser

%package	doc
Summary:	Documentation for %{name}
Group:		Books/Computer books
Requires:	%{name} = %{EVRD}

%description	doc
Documents, RDoc & RI documentation for %{name}.

# FIXME why isn't this autogenerated?
%package debuginfo
Summary:	Debug info for %{name}
Group:		Debug
Requires:	%{name} = %{EVRD}

%description	debuginfo
Debug info for %{name}

%prep
%setup -q -c -T

%install
# NOTE: Putting %%gem_install under the %%build tag will delete some files that should be installed.
%gem_install -d %{buildroot} -n %{SOURCE0}

%files
%{_libdir}/ruby/gems/*/specifications/hpricot-%{version}.gemspec
%{_libdir}/ruby/gems/*/cache/hpricot-%{version}.gem
%{_libdir}/ruby/gems/*/gems/hpricot-%{version}
%{_libdir}/ruby/gems/*/extensions/*/*/hpricot-%{version}

%files doc
%doc %{_libdir}/ruby/gems/*/doc/hpricot-*

%files debuginfo
%{_prefix}/lib/debug%{_libdir}/ruby/gems/*/gems/hpricot-%{version}
%{_prefix}/lib/debug/.dwz/%{name}-*
%{_prefix}/lib/debug%{_libdir}/ruby/gems/*/extensions/*/*/hpricot-%{version}
